# Undisciplining the Victorian Classroom webpage data conversion script
# Script generated by ChatGPT (https://chat.openai.com/chat) then modified by Adrian S. Wisnicki, 2023.
# Takes data entered into the CSV file and places it in the corresponding places in the HTML file, while also renaming the HTML file
# Run via command line with the following: python syllabi.py
# Additional syllabi can be added by removing comments below.

#!/usr/bin/python
import csv
import os

# Define the names of the CSV files and their columns
csv_filenames = {
    'assessment-1': 'spreadsheet-assessment-1.csv',
    # 'assessment-2': 'spreadsheet-assessment-2.csv',
    # 'assessment-3': 'spreadsheet-assessment-3.csv',    
}
csv_columns = ['placeholder', 'text']

# Define the names of the HTML files to update
html_filenames = {
    'assessment-1': 'template-assessment-1.html',
    # 'assessment-2': 'template-assessment-2.html',
    # 'assessment-3': 'template-assessment-3.html',    
}

# Loop over the CSV files and update their corresponding HTML files
for assessment, csv_filename in csv_filenames.items():
    # Open the CSV file and read the data
    with open(csv_filename, 'r') as csvfile:
        # reader = csv.DictReader(csvfile, fieldnames=csv_columns, delimiter='\t')
        reader = csv.DictReader(csvfile, fieldnames=csv_columns)
        data = list(reader)

        # Remove the header row
        data.pop(0)

        # Read the contents of the corresponding HTML file
        html_filename = html_filenames[assessment]
        with open(html_filename, 'r') as f:
            html = f.read()

        # Find the row with "assessment-file-name" in column 1 and get the corresponding value in column 2
        assessment_file_name_row = next((row for row in data if row['placeholder'] == 'assessment-webpage-name'), None)
        if assessment_file_name_row:
            new_html_filename = os.path.splitext(assessment_file_name_row['text'])[0] + '.html'

            # Replace the placeholders in the HTML file with the data from the CSV file
            for row in data:
                html = html.replace('{{{}}}'.format(row["placeholder"]), row["text"])

            # Save the updated HTML file with the new filename
            with open(new_html_filename, 'w') as f:
                f.write(html)
